{{- if .Values.strimzi.enable -}}
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: {{ .Values.strimzi.kafka.deploymentName | default .Release.Name }}
spec:
  kafka:
    replicas: {{ .Values.strimzi.kafka.replicaCount }} 
    listeners:
      plain: {}
      tls: {}
    config:
      num.partitions: {{ .Values.strimzi.kafka.numPartitions }}
      default.replication.factor: {{ .Values.strimzi.kafka.replicationFactor }}
      offsets.topic.replication.factor: {{ .Values.strimzi.kafka.replicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.strimzi.kafka.replicationFactor }}
      transaction.state.log.min.isr: {{ .Values.strimzi.kafka.minIsr }}
      auto.create.topics.enable: {{ .Values.strimzi.kafka.autoTopics }}
    storage:
{{- if .Values.strimzi.kafka.persistStorage }}
      type: persistent-claim
{{ toYaml .Values.strimzi.kafka.storage | indent 6 }}
{{- else }}
      type: ephemeral
{{- end }}
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 15
    rack:
      topologyKey: failure-domain.beta.kubernetes.io/zone
    tlsSidecar:
{{- if .Values.strimzi.tlsSidecar }}
{{ toYaml .Values.strimzi.tlsSidecar | indent 6 }}
{{- else }}
    tlsSidecar: {}
{{- end }}
  zookeeper:
    replicas: {{ .Values.strimzi.kafka.replicaCount }}
    storage:
{{- if .Values.strimzi.zookeeper.persistStorage }}
      type: persistent-claim
{{ toYaml .Values.strimzi.kafka.storage | indent 6 }}
{{- else }}
      type: ephemeral
{{- end }}
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
    tlsSidecar:
{{- if .Values.strimzi.tlsSidecar }}
{{ toYaml .Values.tlsSidecar | indent 6 }}
{{- else }}
    tlsSidecar: {}
{{- end }}
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: "100m"
          memory: 512Mi
        limits:
          cpu: "500m"
          memory: 512Mi
    tlsSidecar:
{{- if .Values.strimzi.tlsSidecar }}
{{ toYaml .Values.tlsSidecar | indent 6 }}
{{- else }}
    tlsSidecar: {}
{{- end }}
{{- end }}
