apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Chart.Name }}
spec:
  limits:
  - default:
      memory: 128Mi
      cpu: 100m
    defaultRequest:
      memory: 128Mi
      cpu: 100m
    type: Container
