apiVersion: v1
kind: ServiceAccount
metadata:
  name: reaper
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: reaper
rules:
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: reaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reaper
subjects:
- kind: ServiceAccount
  name: reaper
  namespace: {{ .Release.Namespace }}
